# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: ${model.getConfig().getMaintainerEmail()}
# Automated tests for ${model.getConfig().getPackageName()}::${class.getSimpleName()}

# R6 ${class.getSimpleName()} instance methods ----

<#list class.getInstanceMethods() as method>
# ├ ${method.getName()}() R6 method ----
	<#if method.hasTests()>
test_that("${class.getSimpleName()}$${method.getName()}() R6 method",	{
		<#if class.hasTestSetup()>
			<#list class.getTestSetup() as testSetup>
${method.indent(testSetup,1)}
			</#list>
		</#if>	
		<#list method.getTests() as test>
${method.indent(test,1)}
		</#list>
})
	</#if>
</#list>

# ${class.getSimpleName()} static methods ----

<#list class.getStaticMethods() as method>
# ├ ${method.getSnakeCaseName()}() package method ----
	<#if method.hasTests()>
test_that("${model.getConfig().getPackageName()}::${method.getSnakeCaseName()}() static method", {
		<#list method.getTests() as test>
${method.indent(test,1)}
		</#list>
})
	</#if>
</#list>