# Generated by roxygen2: do not edit by hand
# But actually generated by r6-generator-maven-plugin
export(JavaApi)
export("%>%")
<#list model.getExports() as export>
export(${export})
</#list>
<#list model.getClassTypes() as class>
	<#list class.getStaticMethods() as method>
export(${method.getSnakeCaseName()})
	</#list>
</#list>
export(.background_cancel)
export(.background_cancel_all)
export(.background_get_by_id)
export(.background_status)
export(.background_tidy_up)

# imports in description but not in namespace. There should be no reason to import these into the namespace.
# however if you don't CRAN complains that "Namespaces in Imports field not imported from:
#    ‘R6’ ...
# All declared Imports should be used."
# even though in fact they are used but maybe outside of function body. 
<#list model.getImports() as import>
import(${import})
</#list>

importFrom(magrittr,"%>%")
importFrom(utils,"capture.output")
import(rJava)
import(R6)