# Generated by r6-generator-maven-plugin: remove this line if you want to make manual changes and dont want them to get overwritten
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
## uncomment this to run on a fixed schedule
#  schedule:
#    # * is a special character in YAML so you have to quote this string
#    - cron:  '0 12 * * *'

name: R-CMD-check

jobs:
  R-CMD-check:

    runs-on: ${r"${{ matrix.config.os }}"}

<#if model.getRelativePath()?has_content>
    defaults:
      run:
        working-directory: ${model.getRelativePath()}

</#if>
    continue-on-error: false

    name: ${r"${{ matrix.config.os }} R:(${{ matrix.config.r }} Java:${{ matrix.config.java }})"}

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-20.04, r: '4.1.0', java: 11, distribution: zulu}
          - {os: macOS-11, r: '4.1.0', java: 11, distribution: zulu}
          - {os: windows-2022, r: '4.1.0', java: 11, distribution: zulu}
          - {os: ubuntu-20.04, r: '3.6.1', java: 8, distribution: zulu}
          - {os: ubuntu-20.04, r: '4.2.0', java: 17, distribution: zulu}
          - {os: ubuntu-20.04, r: 'devel', java: 17, distribution: zulu, http-user-agent: 'release'}


    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${r"${{ matrix.config.rspm }}"}
      GITHUB_PAT: ${r"${{ secrets.GITHUB_TOKEN }}"}

    if: "!contains(github.event.head_commit.message, 'revdepcheck run - No changes to commit')"

    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: actions/setup-java@v3
        with:
          java-version: ${r"${{ matrix.config.java }}"}
          distribution: ${r"${{ matrix.config.distribution }}"}
          java-package: jdk
          architecture: x64
          cache: 'maven'

      - name: Info
        run: "bash -c 'java -version && which java && echo $PATH && echo $JAVA_HOME'"

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${r"${{ matrix.config.r }}"}
          http-user-agent: ${r"${{ matrix.config.http-user-agent }}"}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 3
          extra-packages: any::rcmdcheck any::XML
          needs: check
<#if model.getRelativePath()?has_content>
          working-directory: ${model.getRelativePath()}
</#if>
      
      - name: Setup R Java support
        if: runner.os != 'Windows'
        run: "echo export PATH=$PATH > reconf.sh; echo export JAVA_HOME=$JAVA_HOME >> reconf.sh; echo R CMD javareconf >> reconf.sh; sudo bash reconf.sh"

<#if rToPomPath == "" || rToPomPath == "src">
      # The java code is in the src directory (or a subdirectory of) this will cause issues with windows runners that try and do a R cmd check
	  - name: Rename java source directory for windows
        if: runner.os == 'Windows'
        run: "mv src javasrc"
</#if>

      - uses: r-lib/actions/check-r-package@v2
        with:
          args: 'c("--no-manual", "--no-multiarch", "--as-cran")'
          upload-snapshots: true
<#if model.getRelativePath()?has_content>
          working-directory: ${model.getRelativePath()}
</#if>

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@main
        with:
          name: ${r"${{ matrix.config.os }}"}-${r"${{ matrix.config.r }}"}-${r"${{ matrix.config.java }}"}-results
          path: check
 