# Generated by r6-generator-maven-plugin: remove this line and make manual changes and stop them from being overwritten
# Contact: ${model.getConfig().getMaintainerEmail()}
# Automated tests for ${model.getConfig().getTitle()}}

library(testthat)
library(${model.getConfig().getPackageName()})

test_check("${model.getConfig().getPackageName()}")